# Generated by Django 3.1.4 on 2020-12-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rno', models.IntegerField(default=0)),
                ('marks', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=100)),
                ('clname', models.CharField(default='', max_length=100)),
                ('imageurl', models.CharField(default='', max_length=100)),
                ('tmarks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Totalmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rno', models.IntegerField(default=0)),
                ('totmarks', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=100)),
                ('clname', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
