# Generated by Django 3.1.4 on 2020-12-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='totalmarks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='totalmarks',
            name='fullmarks',
            field=models.IntegerField(default=0),
        ),
    ]
