# Generated by Django 3.1.4 on 2020-12-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Totalmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rno', models.IntegerField(default=0)),
                ('totmarks', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=100)),
                ('clname', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='clname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='history',
            name='imageurl',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='history',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='history',
            name='tmarks',
            field=models.IntegerField(default=0),
        ),
    ]
